name: Build gdm-settings .deb Package

on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build Prerequisites
        id: install-build-prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build gettext cmake unzip curl meson python-gi-dev
          sudo apt-get install build-essential binutils lintian debhelper dh-make devscripts
      - name: Checkout gdm-settings Repository and build
        id: build-gdm-settings-deb-pkg
        run: |
          git clone --depth=1 https://github.com/gdm-settings/gdm-settings && cd "$(basename "$_" .git)"
          meson setup build
          ls -al
          deb_file=$(realpath nvim-linux64.deb)
          echo "::set-output name=deb_file::$deb_file"
