name: Build Neovim .deb Package

on:
  workflow_dispatch:
    inputs:
      arch:
        description: "Target architecture"
        required: true
        default: "amd64"
        type: choice
        options:
          - amd64
          - aarch64

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Set up prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gettext cmake unzip curl \
              build-essential binutils lintian debhelper dh-make devscripts qemu-user-static

      - name: Clone Neovim
        run: |
          git clone https://github.com/neovim/neovim
          cd neovim && git checkout stable

      - name: Build Neovim
        id: build
        run: |
          cd neovim
          make CMAKE_BUILD_TYPE=Release
          cd build
          cpack -G DEB -D CPACK_PACKAGE_FILE_NAME="nvim-stable-linux-${{ github.event.inputs.arch }}"
          deb_path=$(realpath nvim-stable-linux-${{ github.event.inputs.arch }}.deb)
          echo "deb_file=$deb_path" >> "$GITHUB_OUTPUT"

      - name: Parse version number from Git tag
        id: version
        run: |
          version=$(cd neovim && git describe --tags --abbrev=0)
          echo "version_number=${version#v}" >> "$GITHUB_OUTPUT"

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nvim-v${{ steps.version.outputs.version_number }}-stable-linux-${{ github.event.inputs.arch }}
          name: nvim-v${{ steps.version.outputs.version_number }}-stable-linux-${{ github.event.inputs.arch }}
          body: |
            NVIM v${{ steps.version.outputs.version_number }}
            Build type: Release
            Architecture: ${{ github.event.inputs.arch }}
          files: ${{ steps.build.outputs.deb_file }}
