name: Build Neovim .rpm Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build Prerequisites
        id: install-build-prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gettext cmake unzip curl
          sudo apt-get install -y rpm
      
      - name: Checkout Neovim Repository and build
        id: build-nvim-rpm-pkg
        run: |
          git clone https://github.com/neovim/neovim && cd "$(basename "$_" .git)"
          git checkout stable
          make CMAKE_BUILD_TYPE=Release
          cd build && cpack -G RPM
          rpm_file=$(realpath nvim-linux64.rpm)
          echo "rpm_file=$rpm_file" >> $GITHUB_OUTPUT
      
      - name: Parse release info
        id: parse-release-info
        run: |
          release_info=$(curl -s https://api.github.com/repos/neovim/neovim/releases/tags/stable | jq -r '.body' | head -5)
          echo "$release_info"
      
      - name: Parse version number
        id: parse-version-number
        run: |
          version_number=$(curl -s https://api.github.com/repos/neovim/neovim/releases/tags/stable | jq -r '.body' | head -5 | grep -oE "v[0-9]+.[0-9].+[0-9]+")
          echo "version_number=$version_number" >> $GITHUB_OUTPUT
      
      - name: Create Github release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nvim-${{ steps.parse-version-number.outputs.version_number }}-stable-linux-amd64-rpm
          release_name: nvim-${{ steps.parse-version-number.outputs.version_number }}-stable-linux-amd64-rpm
      
      - name: Upload assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ${{ steps.build-nvim-rpm-pkg.outputs.rpm_file }}
          body: ${{ steps.parse-release-info.outputs.release_info }}
          asset_name: nvim-${{ steps.parse-version-number.outputs.version_number }}-stable-linux-amd64.rpm
          asset_content_type: application/x-rpm
