name: Build Neovim .rpm Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm build-essential wget
          sudo apt-get install -y cmake gcc gettext make unzip ninja-build libtool libtool-bin autoconf automake pkg-config gettext

      - name: Set up RPM build environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros

      - name: Download and prepare Neovim source
        run: |
          wget https://github.com/neovim/neovim/archive/refs/tags/stable.tar.gz -O ~/rpmbuild/SOURCES/neovim-stable.tar.gz
          version=$(curl -s https://api.github.com/repos/neovim/neovim/releases/tags/stable | jq -r '.tag_name' | sed 's/^v//')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create RPM spec file
        run: |
          cat << EOF > ~/rpmbuild/SPECS/neovim.spec
          Name:           neovim
          Version:        ${{ env.VERSION }}
          Release:        1%{?dist}
          Summary:        Vim-fork focused on extensibility and usability

          License:        Apache-2.0
          URL:            https://neovim.io/
          Source0:        %{name}-stable.tar.gz

          # Disable automatic dependency processing
          AutoReqProv: no

          %description
          Neovim is a project that seeks to aggressively refactor Vim in order to:
          - Simplify maintenance and encourage contributions
          - Split the work between multiple developers
          - Enable advanced UIs without modifications to the core
          - Maximize extensibility

          %prep
          %setup -q -n %{name}-stable

          %build
          make CMAKE_BUILD_TYPE=Release

          %install
          %make_install

          %files
          %{_bindir}/nvim
          %{_datadir}/nvim/*
          %{_mandir}/man1/nvim.1.*

          %changelog
          * $(date "+%a %b %d %Y") GitHub Action <github-action@example.com> - ${{ env.VERSION }}-1
          - Automated RPM build
          EOF

      - name: Build RPM package
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/neovim.spec
          echo "RPM_FILE=$(ls ~/rpmbuild/RPMS/x86_64/neovim-*.rpm)" >> $GITHUB_ENV

      - name: Display RPM info
        run: |
          echo "RPM file details:"
          file ${{ env.RPM_FILE }}
          rpm -qip ${{ env.RPM_FILE }}

      - name: Create Github release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nvim-${{ env.VERSION }}-stable-linux-amd64-rpm
          release_name: Neovim ${{ env.VERSION }} Stable (Linux AMD64 RPM)

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ${{ env.RPM_FILE }}
          asset_name: neovim-${{ env.VERSION }}-1.x86_64.rpm
          asset_content_type: application/x-rpm

      - name: Verify uploaded asset
        run: |
          asset_url=$(curl -s ${{ steps.create-new-release.outputs.upload_url }} | jq -r '.assets[0].browser_download_url')
          curl -LO $asset_url
          file neovim-*.rpm
          rpm -qip neovim-*.rpm || echo "Failed to query downloaded RPM file"
