name: Rocky8 Build Neovim .rpm Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8
    permissions:
      contents: write
    steps:
      - name: Install Prerequisites
        run: |
          dnf install -y epel-release
          dnf config-manager --set-enabled powertools
          dnf install -y rpm-build wget curl jq make cmake gcc unzip gettext libtool autoconf automake pkg-config ninja-build

      - name: Set up RPM build environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros

      - name: Download and prepare Neovim source
        run: |
          wget https://github.com/neovim/neovim/archive/refs/tags/stable.tar.gz -O ~/rpmbuild/SOURCES/neovim-stable.tar.gz

      - name: Parse release info
        id: parse-release-info
        run: |
          release_info=$(curl -s https://api.github.com/repos/neovim/neovim/releases/tags/stable | jq -r '.body' | head -5)
          echo "$release_info"
      
      - name: Parse version number
        id: parse-version-number
        run: |
          version=$(curl -s https://api.github.com/repos/neovim/neovim/releases/tags/stable | jq -r '.body' | head -5 | grep -oE "v[0-9]+\.[0-9]+\.[0-9]+" | sed 's/^v//')
          echo "VERSION=$version" >> $GITHUB_OUTPUT
          echo "Parsed version: $version"

      - name: Create RPM spec file
        run: |
          cat << EOF > ~/rpmbuild/SPECS/neovim.spec
          Name:           neovim
          Version:        ${{ steps.parse-version-number.outputs.VERSION }}
          Release:        1%{?dist}
          Summary:        Vim-fork focused on extensibility and usability

          License:        Apache-2.0
          URL:            https://neovim.io/
          Source0:        %{name}-stable.tar.gz

          BuildRequires:  make cmake gcc unzip gettext libtool autoconf automake pkg-config ninja-build

          %description
          Neovim is a project that seeks to aggressively refactor Vim in order to:
          - Simplify maintenance and encourage contributions
          - Split the work between multiple developers
          - Enable advanced UIs without modifications to the core
          - Maximize extensibility

          %prep
          %setup -q -n %{name}-stable

          %build
          make CMAKE_BUILD_TYPE=Release

          %install
          rm -rf $RPM_BUILD_ROOT
          mkdir -p %{buildroot}%{_bindir}
          mkdir -p %{buildroot}%{_datadir}/nvim
          cp build/bin/nvim %{buildroot}%{_bindir}/
          cp -r runtime/* %{buildroot}%{_datadir}/nvim/

          %files
          %{_bindir}/nvim
          %{_datadir}/nvim

          %changelog
          * $(date "+%a %b %d %Y") GitHub Action - ${{ steps.parse-version-number.outputs.VERSION }}
          - Automated RPM build
          EOF

      - name: Display spec file
        run: cat ~/rpmbuild/SPECS/neovim.spec

      - name: Build RPM package
        id: build-rpm-package
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/neovim.spec
          echo "RPM_FILE=$(find ~/rpmbuild/RPMS/x86_64/ -name 'neovim-*.rpm' ! -name '*debug*')" >> $GITHUB_OUTPUT

      - name: Debug RPM build output
        if: failure()
        run: |
          echo "Contents of ~/rpmbuild/RPMS:"
          ls -R ~/rpmbuild/RPMS
          echo "Contents of ~/rpmbuild/SRPMS:"
          ls -R ~/rpmbuild/SRPMS
          echo "Last 100 lines of rpmbuild.log:"
          tail -n 100 ~/rpmbuild/BUILD/rpmbuild.log || echo "rpmbuild.log not found"

      - name: Display RPM info
        run: |
          echo "RPM file details:"
          file ${{ steps.build-rpm-package.outputs.RPM_FILE }}
          rpm -qip ${{ steps.build-rpm-package.outputs.RPM_FILE }}
          echo "RPM contents:"
          rpm -qlp ${{ steps.build-rpm-package.outputs.RPM_FILE }}

      - name: Install GitHub CLI
        run: |
          dnf install -y 'dnf-command(config-manager)'
          dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          dnf install -y gh git

      - name: Initialize Git repository
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git init
          git add .
          git commit -m "Initial commit"

      - name: Create Github release and upload asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "nvim-${{ steps.parse-version-number.outputs.VERSION }}-stable-linux-amd64-rpm" \
            --title "Neovim ${{ steps.parse-version-number.outputs.VERSION }} Stable (Linux AMD64 RPM)" \
            --notes "Automated RPM build for Neovim ${{ steps.parse-version-number.outputs.VERSION }}" \
            ${{ steps.build-rpm-package.outputs.RPM_FILE }}

      - name: Verify uploaded asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Waiting for asset to be processed..."
          sleep 15

          echo "Downloading asset..."
          gh release download "nvim-${{ steps.parse-version-number.outputs.VERSION }}-stable-linux-amd64-rpm" -p '*.rpm'

          echo "File details:"
          file *.rpm

          echo "RPM query info:"
          rpm -qip *.rpm || echo "Failed to query downloaded RPM file"

          echo "RPM contents:"
          rpm -qlp *.rpm || echo "Failed to list contents of downloaded RPM file"
