name: Build Neovim .deb Package

on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build Prerequisites
        id: install-build-prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libevent-dev ncurses-dev build-essential bison pkg-config
      - name: download-and-build-tmux
        id: download-and-build-tmux
        run: |
          curl -LsO https://github.com/tmux/tmux/releases/download/3.3a/tmux-3.3a.tar.gz
          tar -zxf tmux-*.tar.gz
          cd tmux-*/
      - name: Create Github release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nvim-${{ steps.parse-version-number.outputs.version_number }}-stable-linux-amd64
          release_name: nvim-${{ steps.parse-version-number.outputs.version_number }}-stable-linux-amd64
      - name: Upload assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ${{ steps.build-nvim-deb-pkg.outputs.deb_file }}
          body: ${{ steps.parse-release-info.outputs.release_info }}
          asset_name: nvim-${{ steps.parse-version-number.outputs.version_number }}-stable-linux-amd64.deb
          asset_content_type: application/vnd.debian.binary-package
